import type { Attention } from "../../../shared/views.ts";

export const ATTENTION: Omit<Attention, "destructive" | "testPath" | "suppressed"> = {
  tickSeconds: 30,
  leadIdleMinutes: 12,
  askWaitingMinutes: 15,
  askLapseMinutes: 45,
  signals: {},
  repeatsAt: 3,
  recoverWithin: 10,
  reworksAt: 3,
  reviewsAt: 3,
  longTurnMinutes: 30,
  longTurnTimes: 3,
  longTurnAfterTurns: 5,
  longTurnMedianOf: 20,
  stuckWithin: 20,
  lookMinutes: 5,
  lookItemChars: 1500,
  quoteChars: 400,
  incidentsKept: 500,
  watcherAnswerMinutes: 15,
  brain: "off",
  sensor: "",
};
